language: python
python:
    - "3.7"
cache: pip
script:
    - pip install awscli
    - cd packages/funding_model
    - python setup.py sdist
    - pip install -e .
    - pytest tests || travis terminate 1;
    - cd ../ml_api
    - pip install -r requirements.txt
    - pytest tests || travis terminate 1;
    - cd ../..
    - aws cp packages/funding_model/dist s3://mypypackages/funding_model --recursive --exclude "*" --include "*.tar.gz"
    - python packages/funding_model/hashing.py || travis terminate 1;
    - eval $(aws ecr get-login --no-include-email --region us-west-1) || travis terminate 1;
    - make build-ml-api-aws tag-ml-api-aws push-ml-api-aws || travis terminate 1;
    - aws ecs update-service --cluster funding-model-cluster --task funding-model-task --service funding-model-service --force-new-deployment
